### ISSUE TITLE
Inline image preview for visual studio?

### ISSUE THREAD

**Issue by magebot1** [viacheslav-lozinskyi/Preview-CSV#2]
Hello, I saw your extension in the marketplace while searching for an extension capable of displaying an inline image preview, I would like to ask if you know any?

I asked on SO:
https://stackoverflow.com/questions/73508446/extension-to-support-inline-image-preview

**Comment by viacheslav-lozinskyi** [comment]
Hello.

If honestly, I don't know such extension.
At least popular extension with such functionality is absent.
I think the reason is next: this functionality supported by standard "Solution Explorer".

![devenv_3dzD9Fnxgc](https://user-images.githubusercontent.com/51988029/187017640-6c2e86f4-3383-4f89-b902-221449b8def3.gif)
